// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts/{id}": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Show an account",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "get login cookie for other requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "login account",
                "parameters": [
                    {
                        "description": "login request",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpserver.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpserver.Response-httpserver_CookieData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpserver.Response-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpserver.CookieData": {
            "type": "object",
            "properties": {
                "siakng_cc": {
                    "type": "string",
                    "default": "2jNeTbVCFfkPIcnUkzwrVw",
                    "x-order": "01"
                },
                "mojavi": {
                    "type": "string",
                    "default": "UrdBjDansj/s95fYW58TfQ",
                    "x-order": "02"
                }
            }
        },
        "httpserver.LoginRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "default": "username",
                    "x-order": "01"
                },
                "password": {
                    "type": "string",
                    "default": "password",
                    "x-order": "02"
                }
            }
        },
        "httpserver.Response-any": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "default": 200,
                    "x-order": "01"
                },
                "message": {
                    "type": "string",
                    "default": "Success",
                    "x-order": "02"
                },
                "data": {
                    "x-order": "03"
                }
            }
        },
        "httpserver.Response-httpserver_CookieData": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "default": 200,
                    "x-order": "01"
                },
                "message": {
                    "type": "string",
                    "default": "Success",
                    "x-order": "02"
                },
                "data": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/httpserver.CookieData"
                        }
                    ],
                    "x-order": "03"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Siak REST API",
	Description:      "This an REST API for siak",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
